
version: 2

sources:
    - name: raw_data
      schema: gz_raw_data
      description: raw data sales gz
     
      tables:
       - name: product
         identifier: raw_gz_product
         description: purchase price by produt_id
       
       - name: ship
         identifier: raw_gz_ship
         description: shipping costs by order_id

       - name: sales
         identifier: raw_gz_sales
         description: revenue and qty by date, order and product